"""v0.1 user exists fix

Revision ID: 7f9c1bf5c8b2
Revises: c5e522c1ad64
Create Date: 2022-12-10 14:53:42.731051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9c1bf5c8b2'
down_revision = 'c5e522c1ad64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'User', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    # ### end Alembic commands ###
