"""v0.1 database create fix

Revision ID: 96c40ba7525f
Revises: 23b7fef05968
Create Date: 2022-12-13 10:21:09.080599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c40ba7525f'
down_revision = '23b7fef05968'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
